In [1]:
import torch

In [8]:
def activation(x):
    """
    sigmoid activation function
    """
    return 1/(1+torch.exp(-x))

In [2]:
torch.manual_seed(7)

features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.rand((1,1))

In [19]:
y = activation(torch.sum(features * weights) + bias)

In [20]:
y

tensor([[0.2504]])

In [35]:
features #* weights

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [36]:
weights.t()

tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])

In [34]:
activation(torch.mm(features, weights.t()) + bias)

tensor([[0.2504]])

In [29]:
activation(torch.sum(features * weights) + bias)

tensor([[0.2504]])

In [30]:
activation((features * weights).sum() + bias)

tensor([[0.2504]])

In [38]:
activation(torch.mm(features, weights.view(5,1)) + bias)

tensor([[0.2504]])

In [17]:
#result = torch.mm(features, weights.t())

In [18]:
#result1 = torch.sum(result, bias)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input)
 * (Tensor input, torch.dtype dtype)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor)
 * (Tensor input, tuple of ints dim, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, torch.dtype dtype, Tensor out)
 * (Tensor input, tuple of ints dim, bool keepdim, Tensor out)
